#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    blockFling,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MoveCommands.h"

void autoInitialize()
{
	// Grajales recommended this as the starting value for spinner.  Do not change.
	servoTarget[blockFling] = 255;
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[spinner] = 0;
}

task main()
{
	//waitForStart();

	move_forward(5.0, 5000, 70, 70);
	wait1Msec(500);

	move_forward(1.0, 5000, 70, 70);
	wait1Msec(500);

	turngyro_right(90, 50);
	wait1Msec(500);

	move_forward(3.0, 5000, 70, 70);
	wait1Msec(500);

	servoTarget[blockFling] = 0;
	wait1Msec(1500);

	servoTarget[blockFling] = 10;
	wait1Msec(1500);

	servoTarget[blockFling] = 0;
	wait1Msec(1500);

	servoTarget[blockFling] = 255;
	wait1Msec(500);

	move_forward(1.0, 5000, 70, 70);
	wait1Msec(500);

	turngyro_right(90, 50);
	wait1Msec(500);

	// Note:  2 and a half feet is an estimated number for the length between the basket and ramp.
	// Subject to change.
	move_forward(3, 5000, 70, 70);


	stop_all_motors();
}
